# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
absolute_permalinks: true

# Setup
title:               Rohan
tagline:             ''
description:         'Portfolio website of <a href="https://www.linkedin.com/in/rohan-mark-gomes" target="_blank">Rohan Mark Gomes</a> . Github username: <a href="https://github.com/DarkStar1997" target="_blank">DarkStar1997</a>.'
url:                 https://github.com/DarkStar1997
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Rohan Mark Gomes
  url:               https://www.linkedin.com/in/rohan-mark-gomes/
  email:             rohanmarkgomes@gmail.com

# Custom vars
version:             1.0.0