# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
absolute_permalinks: true

# Setup
title:               DarkStar1997
tagline:             'Home'
description:         'Portfolio website of Rohan Mark Gomes'
url:                 https://github.com/DarkStar1997
baseurl:             'https://github.com/DarkStar1997'
paginate:            5

# About/contact
author:
  name:              Rohan Mark Gomes
  url:               https://www.linkedin.com/in/rohan-mark-gomes/
  email:             rohanmarkgomes@gmail.com

# Custom vars
version:             1.0.0
